#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/inventorydb
#    username: postgres
#    password: 123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          time_zone: Asia/Phnom_Penh
#  jackson:
#    time-zone: Asia/Phnom_Penh
#
##  rustfs.url=http://localhost:9000
##  rustfs.access.name=${RUSTFS_ACCESS_KEY}
##  rustfs.access.secret=${RUSTFS_SECRET_KEY}
##  rustfs.bucket.name=demo-file-upload
#
